export const addressesConstants = {
    GET_ADDRESS_REQUEST: "@address/GET_ADDRESS_REQUEST",
    GET_ADDRESS_SUCCESS: "@address/GET_ADDRESS_SUCCESS",
    GET_ADDRESS_FAIL: "@address/GET_ADDRESS_FAIL",

    TOGGLE_IS_VERIFIED: "@address/TOGGLE_IS_VERIFIED",

    VERIFY_ADDRESS_REQUEST: "@address/VERIFY_ADDRESS_REQUEST",
    VERIFY_ADDRESS_SUCCESS: "@address/VERIFY_ADDRESS_SUCCESS",
    VERIFY_ADDRESS_FAIL: "@address/VERIFY_ADDRESS_FAIL",

};
