/**
 * Created by vladtomsa on 26/11/2018
 */
export const addressesConstants = {
  ON_GET_ADDRESSES_INIT: '@ON_GET_ADDRESSES_INIT',
  ON_GET_ADDRESSES_SUCCESS: '@ON_GET_ADDRESSES_SUCCESS',
  ON_GET_ADDRESSES_FAILURE: '@ON_GET_ADDRESSES_FAILURE',

  ON_GET_ADDRESSES_DETAILS_INIT: '@ON_GET_ADDRESSES_DETAILS_INIT',
  ON_GET_ADDRESSES_DETAILS_SUCCESS: '@ON_GET_ADDRESSES_DETAILS_SUCCESS',
  ON_GET_ADDRESSES_DETAILS_FAILURE: '@ON_GET_ADDRESSES_DETAILS_FAILURE',

  ON_GET_ADDRESSES_TRANSACTIONS_FLOW_INIT: '@ON_GET_ADDRESSES_TRANSACTIONS_FLOW_INIT',
  ON_GET_ADDRESSES_TRANSACTIONS_FLOW_SUCCESS: '@ON_GET_ADDRESSES_TRANSACTIONS_FLOW_SUCCESS',
  ON_GET_ADDRESSES_TRANSACTIONS_FLOW_FAILURE: '@ON_GET_ADDRESSES_TRANSACTIONS_FLOW_FAILURE',

  ON_SELECT_ADDRESS: '@ON_SELECT_ADDRESS'
};
