export const transactionConstants = {
    GET_ADDRESS_TRANSACTIONS_REQUEST: "@transaction/GET_ADDRESS_TRANSACTIONS_REQUEST",
    GET_ADDRESS_TRANSACTIONS_SUCCESS: "@transaction/GET_ADDRESS_TRANSACTIONS_SUCCESS",
    GET_ADDRESS_TRANSACTIONS_FAIL: "@transaction/GET_ADDRESS_TRANSACTIONS_FAIL",

    GET_ADDRESS_FLOW_REQUEST: "@transaction/GET_ADDRESS_FLOW_REQUEST",
    GET_ADDRESS_FLOW_SUCCESS: "@transaction/GET_ADDRESS_FLOW_SUCCESS",
    GET_ADDRESS_FLOW_FAIL: "@transaction/GET_ADDRESS_FLOW_FAIL",
};
